### PR TITLE
Meeting notes (2020 02 12)

### PR DESCRIPTION
**Pull request by leodido**

### CODE REVIEW

**Comment by leodido** [comment]
/hold

Hold until we verify is anybody recorded the meeting or not.

**Comment by leodido** [comment]
Hey @rajibmitra and @Issif do you have the recording link?

**Comment by Issif** [comment]
I didn't recorded for my part. Don't know if @rajibmitra did.

**Comment by leodido** [comment]
Ok, let's merge anyway.

**Comment by Issif** [comment]
LGTM
/approve

**Pull request merged**
