### PR TITLE
falco-newsletter-feb2023

### PR DESCRIPTION
**Pull request by jsalinas29**
uploading first v of the falco monthly newsletter

### CODE REVIEW

**Comment by Andreagit97** [comment]
ei @jsalinas29 you miss the DCO on one of your commits since it seems that there is a strange merge commit between them, I would suggest you to squash them :) this is how I would do it:

```bash
git checkout <your-branch-name>
git reset HEAD~2
git add .
git commit -s --amend
```

Moreover, just a minor suggestion: when you open a pull request the best practice is to do it from a new local branch not directly from your `main` local branch.  In this way you will avoid commit like this https://github.com/falcosecurity/community/commits/a765607fde0647d70fc9fa85ddaa82ba0e5859b3

**Comment by jsalinas29** [comment]
oops - yeah, sorry still getting the hang of this. can i just kill this pr?

**Comment by Andreagit97** [comment]
> oops - yeah, sorry still getting the hang of this. can i just kill this pr?

Yep feel free to do that if you prefer :)

**Review by leogr — COMMENTED** [review]
Could you also put this under a dedicated folder (for example, `/newsletter`)?

Thank you!

**Comment by jsalinas29** [comment]
git checkout <jsalinas29>
git reset HEAD~2
git add .
git commit -s --amend

**Comment by jsalinas29** [comment]
closing and starting over...

**Pull request closed without merging**
