### PR TITLE
feat(docs): Adding documentation for releases managing the meeting notes

### PR DESCRIPTION
**Pull request by kris-nova**
Signed-off-by: Kris Nóva <kris@nivenly.com>

### CODE REVIEW

**Review by nibalizer — APPROVED** [review]

**Comment by nibalizer** [comment]
+1 from me

**Review by leodido — COMMENTED** [review]
Agreed on this.

As a side note: the zoom recordings will be updated after each community call or we'll go live?

**Comment by leogr** [comment]
> Agreed on this.
> 
> As a side note: the zoom recordings will be updated after each community call or we'll go live?

I'd prefer to go live, if possible :)

**Comment by fntlnz** [comment]
Adding an hold to let others PR get in, once this is ready the hold can be removed.

/hold

**Pull request closed without merging**
